
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 512
WIDTH = SCREEN_WIDTH // 2
HEIGHT = SCREEN_HEIGHT // 2
SCREEN_CENTER = [WIDTH//2, HEIGHT//2]
FPS = 60
CELL_SIZE = 16
COLS = WIDTH // CELL_SIZE
ROWS = HEIGHT // CELL_SIZE

RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
SKY_BLUE = (70, 210, 255)
YELLOW = ()

# ---- PATHS
SRC_PATH = 'src/'
ASSET_PATH = 'src/assets/'
MAP_PATH = f'{SRC_PATH}maps/'

FONTS_PATH = f'{SRC_PATH}/fonts/'
IMG_PATH = f'{ASSET_PATH}images/'
ANIM_PATH = f'{IMG_PATH}animations/'
LIGHTS_PATH = f'{IMG_PATH}lights/'
PARTS_PATH = f'{IMG_PATH}parts/'

TILE_PATH = f'{ASSET_PATH}tiles/'
TILESET_PATH = f'{TILE_PATH}tileset/'
OBJECT_PATH = f'{TILE_PATH}objects/'

AUDIO_PATH = f'{ASSET_PATH}audio/'

